CREATE DATABASE IF NOT EXISTS FREEBIES_APP;

USE FREEBIES_APP;

CREATE TABLE item(
id int NOT NULL AUTO_INCREMENT,
description TEXT,
image TEXT,
location VARCHAR(255),
name VARCHAR(255),
price VARCHAR(255),
zipcode VARCHAR(255),
category VARCHAR(255),
PRIMARY KEY(id)

);
